### ISSUE TITLE
Build failure on Mageia 5 with latest 5.0.0 version

### ISSUE THREAD

**Issue by david-geiger** [rupeshs/ExMplayer#12]
Hello,

I can't build exmplayer-5.0.0 on Mageia 5, I get this compile issue (past of full compile log):

http://pastebin.com/zpNJKk5A

Regards David.

**Comment by rupeshs** [comment]
Hi David,
Today I released builds for Ubuntu,Fedora 21.
http://exmplayer.sourceforge.net/downloads.html
Build Steps
---------------
Please use this spec file  
https://github.com/rupeshs/ExMplayer/blob/master/exmplayer.spec
Qt Version 4.7.4
And follow the steps
https://ask.fedoraproject.org/en/question/63023/installing-exmplayer-to-fedora/

Regards Rupesh

**Comment by david-geiger** [comment]
Hi Rupesh,

Is that normal that I have this warning during compilation of 5.0.1 version ?

make: Warning: File 'src/ExMplayer.pro' has modification time 8298 s in the future

**Comment by rupeshs** [comment]
Dont worry ,it will compile

**Comment by david-geiger** [comment]
So ok, now exmplayer-5.0.1 has built fine on Mageia Build system. :)

Thanks a lot for your good work Rupesh !

**Comment by rupeshs** [comment]
Welcome :)
