### ISSUE TITLE
mplayer2 support

### ISSUE THREAD

**Issue by HighCommander4** [rupeshs/ExMplayer#15]
The current Debian stable distro has `mplayer2` available, but not `mplayer`.

It would be nice if this program could use `mplayer2` as well.

**Comment by rupeshs** [comment]
Mplayer 2 project not actively developed so mplayer2 is not a good option

**Comment by HighCommander4** [comment]
Ok. For anyone else running into this, `mplayer` can be installed on Debian via http://www.deb-multimedia.org/
