### ISSUE TITLE
release amd64.deb packages and AppImages

### ISSUE THREAD

**Issue by freddii** [rupeshs/ExMplayer#20]
It would be nice to have amd64.deb packages and AppImages releases at:
https://github.com/rupeshs/ExMplayer/releases

**Comment by rupeshs** [comment]
Please use 
https://launchpad.net/~exmplayer-dev/+archive/ubuntu/exmplayer/+packages

**Comment by freddii** [comment]
its missing a package for  Ubuntu 20.04 LTS (Focal Fossa)

**Comment by rupeshs** [comment]
Started ExMplayer Qt4 to Qt5  code migration

**Comment by rupeshs** [comment]
@freddii  
ExMplayer Qt5 porting completed
To install 
sudo add-apt-repository ppa:exmplayer-dev/exmplayer-qt5
sudo apt-get update
sudo apt-get install exmplayer  

https://launchpad.net/~exmplayer-dev/+archive/ubuntu/exmplayer-qt5

**Comment by Fak3** [comment]
can i find rpm or appimage or flatpak of qt5 version?

**Comment by rupeshs** [comment]
@Fak3 You can build rpm package.
