### ISSUE TITLE
install in Fedora 21

### ISSUE THREAD

**Issue by ahloiscreamo** [rupeshs/ExMplayer#9]
hi,can you guide me on how to compile under fedora.
thanks

**Comment by rupeshs** [comment]
ExMplayer for Fedora(rpm package) will be available soon.

**Comment by rupeshs** [comment]
ExMplayer rpm available for fedora 21 http://sourceforge.net/projects/exmplayer/files/ExMplayer-3.8.0-beta/

**Comment by rupeshs** [comment]
ExMplayer rpm available for fedora 21 http://sourceforge.net/projects/exmplayer/files/ExMplayer-3.8.0-beta/
